when:
  - event: push
    branch: main

steps:
  - name: build-image
    image: docker
    commands:
      - docker build --rm -t sample-nginx .
    volumes:
      - /var/run/podman.sock:/var/run/docker.sock
