when:
  - event: push
    branch: main

steps:
  - name: build-image
    image: quay.io/podman/stable
    commands:
      - podman build --rm -t sample-nginx .
    volumes:
      - /var/run/podman.sock:/var/run/podman.sock
      - /var/lib/containers:/var/lib/containers
